version: "3.9"
services:
  web:
    image: my_nginx
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - "./index.html:/usr/share/nginx/html/index.html"
    environment:
      - NODE_ENV=prod
